name: starformer
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - cudatoolkit=11.3.1
  - future
  - hdf5
  - pillow
  - pip
  - python=3.9
  - pytorch=1.9.0
  - setuptools=59.5.0
  - timm=0.4.12
  - torchvision=0.10.1
  - torchaudio=0.9.0
  - pip:
    - atari-py==0.2.9
    - blosc
    - dm-control==1.0.3
    - einops
    - gym==0.18.3
    - h5py
    - lxml
    - matplotlib
    - mujoco==2.2.0
    - mujoco-py==2.1.2.14
    - numpy
    - opencv-python
    - pandas
    - scipy
    - tensorboard
    - tensorflow
    - tqdm
    - git+https://github.com/google/dopamine.git@dabc84b1013b7ced981f189b2bb161e7fa94d31a